from enum import Enum, auto


class Country(Enum):
    AC = auto()  # Antigua and Barbuda
    AE = auto()  # United Arab Emirates
    AF = auto()  # Afghanistan
    AG = auto()  # Algeria
    AJ = auto()  # Azerbaijan
    AL = auto()  # Albania
    AM = auto()  # Armenia
    AO = auto()  # Angola
    AQ = auto()  # American Samoa [United States]
    AR = auto()  # Argentina
    AS = auto()  # Australia
    AU = auto()  # Austria
    AY = auto()  # Antarctica
    BA = auto()  # Bahrain
    BB = auto()  # Barbados
    BC = auto()  # Botswana
    BD = auto()  # Bermuda [United Kingdom]
    BE = auto()  # Belgium
    BF = auto()  # Bahamas, The
    BG = auto()  # Bangladesh
    BH = auto()  # Belize
    BK = auto()  # Bosnia and Herzegovina
    BL = auto()  # Bolivia
    BM = auto()  # Burma
    BN = auto()  # Benin
    BO = auto()  # Belarus
    BP = auto()  # Solomon Islands
    BR = auto()  # Brazil
    BU = auto()  # Bulgaria
    BX = auto()  # Brunei
    BY = auto()  # Burundi
    CA = auto()  # Canada
    CB = auto()  # Cambodia
    CD = auto()  # Chad
    CE = auto()  # Sri Lanka
    CF = auto()  # Congo (Brazzaville)
    CG = auto()  # Congo (Kinshasa)
    CH = auto()  # China
    CI = auto()  # Chile
    CJ = auto()  # Cayman Islands [United Kingdom]
    CK = auto()  # Cocos (Keeling) Islands [Australia]
    CM = auto()  # Cameroon
    CO = auto()  # Colombia
    CQ = auto()  # Northern Mariana Islands [United States]
    CS = auto()  # Costa Rica
    CT = auto()  # Central African Republic
    CU = auto()  # Cuba
    CV = auto()  # Cape Verde
    CW = auto()  # Cook Islands [New Zealand]
    CY = auto()  # Cyprus
    DA = auto()  # Denmark
    DO = auto()  # Dominica
    DR = auto()  # Dominican Republic
    EC = auto()  # Ecuador
    EG = auto()  # Egypt
    EI = auto()  # Ireland
    EK = auto()  # Equatorial Guinea
    EN = auto()  # Estonia
    ER = auto()  # Eritrea
    ES = auto()  # El Salvador
    ET = auto()  # Ethiopia
    EU = auto()  # Europa Island [France]
    EZ = auto()  # Czech Republic
    FG = auto()  # French Guiana [France]
    FI = auto()  # Finland
    FJ = auto()  # Fiji
    FK = auto()  # Falkland Islands (Islas Malvinas) [United Kingdom]
    FM = auto()  # Federated States of Micronesia
    FP = auto()  # French Polynesia
    FR = auto()  # France
    FS = auto()  # French Southern and Antarctic Lands [France]
    GA = auto()  # Gambia, The
    GB = auto()  # Gabon
    GG = auto()  # Georgia
    GH = auto()  # Ghana
    GI = auto()  # Gibraltar [United Kingdom]
    GL = auto()  # Greenland [Denmark]
    GM = auto()  # Germany
    GP = auto()  # Guadeloupe [France]
    GQ = auto()  # Guam [United States]
    GR = auto()  # Greece
    GT = auto()  # Guatemala
    GV = auto()  # Guinea
    GY = auto()  # Guyana
    HO = auto()  # Honduras
    HR = auto()  # Croatia
    HU = auto()  # Hungary
    IC = auto()  # Iceland
    ID = auto()  # Indonesia
    IN = auto()  # India
    IO = auto()  # British Indian Ocean Territory [United Kingdom]
    IR = auto()  # Iran
    IS = auto()  # Israel
    IT = auto()  # Italy
    IV = auto()  # Cote D'Ivoire
    IZ = auto()  # Iraq
    JA = auto()  # Japan
    JM = auto()  # Jamaica
    JN = auto()  # Jan Mayen [Norway]
    JO = auto()  # Jordan
    JQ = auto()  # Johnston Atoll [United States]
    JU = auto()  # Juan De Nova Island [France]
    KE = auto()  # Kenya
    KG = auto()  # Kyrgyzstan
    KN = auto()  # Korea, North
    KR = auto()  # Kiribati
    KS = auto()  # Korea, South
    KT = auto()  # Christmas Island [Australia]
    KU = auto()  # Kuwait
    KZ = auto()  # Kazakhstan
    LA = auto()  # Laos
    LE = auto()  # Lebanon
    LG = auto()  # Latvia
    LH = auto()  # Lithuania
    LI = auto()  # Liberia
    LO = auto()  # Slovakia
    LQ = auto()  # Palmyra Atoll [United States]
    LT = auto()  # Lesotho
    LU = auto()  # Luxembourg
    LY = auto()  # Libya
    MA = auto()  # Madagascar
    MB = auto()  # Martinique [France]
    MC = auto()  # Macau S.A.R
    MD = auto()  # Moldova
    MF = auto()  # Mayotte [France]
    MG = auto()  # Mongolia
    MI = auto()  # Malawi
    MJ = auto()  # Montenegro
    MK = auto()  # Macedonia
    ML = auto()  # Mali
    MO = auto()  # Morocco
    MP = auto()  # Mauritius
    MQ = auto()  # Midway Islands [United States}
    MR = auto()  # Mauritania
    MT = auto()  # Malta
    MU = auto()  # Oman
    MV = auto()  # Maldives
    MX = auto()  # Mexico
    MY = auto()  # Malaysia
    MZ = auto()  # Mozambique
    NC = auto()  # New Caledonia [France]
    NE = auto()  # Niue [New Zealand]
    NF = auto()  # Norfolk Island [Australia]
    NG = auto()  # Niger
    NH = auto()  # Vanuatu
    NI = auto()  # Nigeria
    NL = auto()  # Netherlands
    NN = auto()  # Sint Maarten
    NO = auto()  # Norway
    NP = auto()  # Nepal
    NS = auto()  # Suriname
    NU = auto()  # Nicaragua
    NZ = auto()  # New Zealand
    PA = auto()  # Paraguay
    PC = auto()  # Pitcairn Islands [United Kingdom]
    PE = auto()  # Peru
    PK = auto()  # Pakistan
    PL = auto()  # Poland
    PM = auto()  # Panama
    PO = auto()  # Portugal
    PP = auto()  # Papua New Guinea
    PS = auto()  # Palau
    PU = auto()  # Guinea-Bissau
    QA = auto()  # Qatar
    RE = auto()  # Reunion [France]
    RI = auto()  # Serbia
    RM = auto()  # Marshall Islands
    RO = auto()  # Romania
    RP = auto()  # Philippines
    RQ = auto()  # Puerto Rico [United States]
    RS = auto()  # Russia
    RW = auto()  # Rwanda
    SA = auto()  # Saudi Arabia
    SB = auto()  # Saint Pierre and Miquelon [France]
    SE = auto()  # Seychelles
    SF = auto()  # South Africa
    SG = auto()  # Senegal
    SH = auto()  # Saint Helena [United Kingdom]
    SI = auto()  # Slovenia
    SL = auto()  # Sierra Leone
    SN = auto()  # Singapore
    SP = auto()  # Spain
    ST = auto()  # Saint Lucia
    SU = auto()  # Sudan
    SV = auto()  # Svalbard [Norway]
    SW = auto()  # Sweden
    SX = auto()  # South Georgia and the South Sandwich Islands [United Kingdom]
    SY = auto()  # Syria
    SZ = auto()  # Switzerland
    TD = auto()  # Trinidad and Tobago
    TE = auto()  # Tromelin Island [France]
    TH = auto()  # Thailand
    TI = auto()  # Tajikistan
    TL = auto()  # Tokelau [New Zealand]
    TN = auto()  # Tonga
    TO = auto()  # Togo
    TS = auto()  # Tunisia
    TU = auto()  # Turkey
    TV = auto()  # Tuvalu
    TX = auto()  # Turkmenistan
    TZ = auto()  # Tanzania
    UC = auto()  # Curacao
    UG = auto()  # Uganda
    UK = auto()  # United Kingdom
    UP = auto()  # Ukraine
    US = auto()  # United States
    UV = auto()  # Burkina Faso
    UY = auto()  # Uruguay
    UZ = auto()  # Uzbekistan
    VE = auto()  # Venezuela
    VM = auto()  # Vietnam
    VQ = auto()  # Virgin Islands [United States]
    WA = auto()  # Namibia
    WF = auto()  # Wallis and Futuna [France]
    WI = auto()  # Western Sahara
    WQ = auto()  # Wake Island [United States]
    WZ = auto()  # Swaziland
    ZA = auto()  # Zambia
    ZI = auto()  # Zimbabwe
